# Default values for argo-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ports:
  client: 3000
  server: 5000
  postgres: 5432
  mongoport: 27017
  mockerserver: 8084
