apiVersion: v1
kind: Service
metadata:
  name: mockserver-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mockserver
  ports:
    - port: {{.Values.ports.mockerserver}}
      targetPort: 8084
