apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mongodb
  ports:
    - port: {{.Values.ports.mongoport}}
      targetPort: 27017
