apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      labels:
        component: mongo
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
